print("Гpyna 4")
text_file = open("D:\students4.txt", "wt")
text_file.write("Жак Фреско, 0 балів\n")
text_file.write("Максим Максимов, 0 балів\n")
text_file.write("Іван Іванов, 0 балів\n")
text_file.write("Яша Лава, 0 балів\n")
text_file.close()

print("Гpyna 5")
text_file = open("D:\students5.txt", "wt")
text_file.write("Сосу Бибу, 0 балів\n")
text_file.write("Нестор Махно, 0 балів\n")
text_file.write("Ілларион Великий, 0 балів\n")
text_file.write("Герман Ауєшникович, 0 балів\n")
text_file.close()

print("Гpyna 6")
text_file = open("D:\students6.txt", "wt")
text_file.write("Глад Валакас, 0 балів\n")
text_file.write("Внук Гітлера, 0 балів\n")
text_file.write("Михуїл Турчинський, 0 балів\n")
text_file.write("Денис Сухина, 0 балів\n")
text_file.close()